# Generated by Django 4.2.26 on 2025-12-01 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='requires_prescription',
        ),
    ]
