# Generated by Django 4.2.26 on 2025-12-03 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Giriş Yaptı'), ('LOGOUT', 'Çıkış Yaptı'), ('REGISTER', 'Kayıt Oldu'), ('ADD_CART', 'Sepete Ekleme'), ('REMOVE_CART', 'Sepetten Silme'), ('ORDER', 'Sipariş Verme')], max_length=20, verbose_name='İşlem Türü')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zaman')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Logu',
                'verbose_name_plural': 'Kullanıcı Hareketleri & Güvenlik Logları',
                'ordering': ['-timestamp'],
            },
        ),
    ]
