# Generated by Django 4.2.26 on 2025-12-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_updated',
            field=models.BooleanField(default=False, verbose_name='Düzenlendi mi?'),
        ),
    ]
