"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.26.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ld+^^)(y38+sqjz^10k%-46##w=m)77#h%bh5p95t-(0l@s6=7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # <-- Django'ya "Ana klasördeki templates'e bak" diyoruz
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.cart_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'e_eczane_db',    # Terminalde oluşturduğun DB adı
        'USER': 'fatihbiyikli',   # Mac kullanıcı adın
        'PASSWORD': '',           # Boş bırakıyoruz
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# settings.py EN ALTI

JAZZMIN_SETTINGS = {
    # Site Başlığı
    "site_title": "E-Eczane Admin",
    "site_header": "E-Eczane Yönetim",
    "site_brand": "E-Eczane Paneli",
    "welcome_sign": "Yönetim Paneline Hoşgeldiniz",
    "copyright": "KTÜ Yazılım Mühendisliği",
    
    # Kullanıcı Menüsü
    "topmenu_links": [
        # Url kısmına 'home' yerine 'product_list' yazıyoruz (senin ana sayfa ismin)
        {"name": "Siteyi Görüntüle",  "url": "product_list", "permissions": ["auth.view_user"], "icon": "fas fa-home"},
    ],

    # Sol Menü Düzeni
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # İkonlar (FontAwesome kullanıyoruz)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        # Bizim Modeller:
        "store.Product": "fas fa-pills",           # İlaç/Ürün İkonu
        "store.Category": "fas fa-list",           # Kategori
        "store.Order": "fas fa-shopping-cart",     # Sipariş
        "store.Review": "fas fa-star",             # Yorumlar
        "store.UserActivityLog": "fas fa-shield-alt", # GÜVENLİK (Blue Team)
    },
}

# Renk Teması (Modern ve Ciddi)
JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",  # Bootstrap teması
    "navbar": "navbar-dark bg-success", # Eczane yeşili
    "sidebar": "sidebar-dark-success",  # Menü de koyu yeşil uyumlu
}




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Giriş yapınca ana sayfaya git
LOGIN_REDIRECT_URL = '/'
# Çıkış yapınca ana sayfaya git
LOGOUT_REDIRECT_URL = '/'